apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
  interval: 10m
  path: ./clusters/staging/external-secrets-operator/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
