apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- external-secrets-operator-kustomization.yaml
- external-secrets-resources-kustomization.yaml
- cluster-autoscaler-kustomization.yaml
- gateway-api-crds-kustomization.yaml
- nginx-gateway-kustomization.yaml
- cert-manager-kustomization.yaml
- cert-manager-secrets-kustomization.yaml
- cert-manager-resources-kustomization.yaml
- external-dns-kustomization.yaml
- gateway-kustomization.yaml
- utro-kustomization.yaml
- utro-bootstrap-kustomization.yaml
- utro-route-kustomization.yaml
- storage-kustomization.yaml
- observability-kustomization.yaml
- observability-resources-kustomization.yaml
- cloudflared-kustomization.yaml
