apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-hello
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: demo-hello
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: lit/staging/demo/hello
        property: message
